### ISSUE TITLE
fix clock speed

### ISSUE THREAD

**Issue by r0x57n** [LiU-SeeGoals/robot#12]
Currently (according to MX) it's clocked at 64 MHz, it should be capable of ~480 MHz (https://www.st.com/en/microcontrollers-microprocessors/stm32h7-series.html). I think it set itself to 64 when running "Resolve Clock Issues" when we were trying to setup SPI.

**Comment by haholm** [comment]
Clock configuration might have caused a board to stop working. ST-Link seems to work but "No target found on device" displayed when trying to flash/attach debugger. Needs to be troubleshot before proceeding.

**Comment by r0x57n** [comment]
fixed, can flash it now again, I created this page which we can keep updated https://github.com/LiU-SeeGoals/wiki/wiki/3.1.-Debugging-devboards

I'm pretty sure all that was needed was to set mode to `Power down`, but not sure.
