### ISSUE TITLE
Configurations

### ISSUE THREAD

**Issue by r0x57n** [LiU-SeeGoals/robot#3]
Each robot will have to have it's unique RF receive address, and these should be stored locally on the robot somehow. I got two ideas, one ugly and one nice.
Nice: Can we attach SD cards to the H7 and store it there?
Ugly: We keep each robot's individual configuration in the robot firmware and identify what robot is currently running it through its MAC address or serial number or whatever we can identify it through. From that we choose what RF receive address to set and other robot specific configuration.

**Comment by Paladinking** [comment]
The ugly solution is implemented. If we get some non-volatile memory on the robots, this could be worth revisiting.
