### ISSUE TITLE
Receive vision packets on different pipe

### ISSUE THREAD

**Issue by r0x57n** [LiU-SeeGoals/robot#4]
We can't really know whether we receive an SSL packet or controller packet through RF, so decoding will be hard. But using different pipes for different packet types should fix that without much issue. We could create some kind of wrapper as well, but that seems harder really.

**Comment by Paladinking** [comment]
This turned out to be a lot more complicated than it would seem, and not worth the gain. Also less relevant now that basestation does not receive raw SSL-vision data. Instead, a single id byte is used in each message to identify the source.
